create table if not exists customer_orders (
  id uuid primary key default gen_random_uuid(),
  entry_date date,
  customer_name text,
  work_order_number text,
  po_number text,
  phone_1 text,
  phone_2 text,
  phone_3 text,
  email text,
  address text,
  apt_unit_number text,
  city text,
  state text,
  zip_code text,
  store_number text,
  job_type text,
  labor_to_do text,
  instructions text,
  materials text,
  auto_date timestamptz,
  date_order_sent_to_installer date,
  material_arrival_date date,
  do_not_send_to_installer boolean,
  schedule_date timestamptz,
  last_note_made text,
  scheduled_in_ix boolean,
  scheduled_in_installerx boolean,
  time_window text,
  latest_comment text,
  dup_check text,
  attributes jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
); 