CREATE TABLE IF NOT EXISTS communication_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ WITH TIME ZONE DEFAULT NOW() NOT NULL,
  type TEXT NOT NULL, -- e.g., 'proposal_sent', 'customer_reply', 'alert', etc.
  message TEXT NOT NULL,
  order_id UUID,
  customer_id TEXT,
  direction TEXT, -- 'inbound' or 'outbound'
  channel TEXT, -- 'sms', 'slack', etc.
  status TEXT, -- e.g., 'sent', 'delivered', 'failed', 'read'
  context JSONB
);

COMMENT ON COLUMN communication_logs.type IS 'Type of communication event (proposal_sent, customer_reply, etc)';
COMMENT ON COLUMN communication_logs.message IS 'Message content or summary';
COMMENT ON COLUMN communication_logs.order_id IS 'Related order UUID, if applicable';
COMMENT ON COLUMN communication_logs.customer_id IS 'Related customer identifier, if applicable';
COMMENT ON COLUMN communication_logs.direction IS 'Direction: inbound (from customer) or outbound (to customer)';
COMMENT ON COLUMN communication_logs.channel IS 'Channel: sms, slack, etc.';
COMMENT ON COLUMN communication_logs.status IS 'Status of the communication (sent, delivered, failed, read, etc)';
COMMENT ON COLUMN communication_logs.context IS 'Additional context as JSON (raw payload, metadata, etc)'; 