CREATE TABLE public.system_alerts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ WITH TIME ZONE DEFAULT NOW() NOT NULL,
  type TEXT NOT NULL, -- e.g., 'unknown_line_item'
  message TEXT NOT NULL,
  context JSONB, -- To store the full Smartsheet payload for debugging
  status TEXT DEFAULT 'new' NOT NULL, -- e.g., 'new', 'acknowledged', 'resolved'
  work_order_number TEXT
);

COMMENT ON COLUMN public.system_alerts.type IS 'The type of alert, e.g., "unknown_line_item".';
COMMENT ON COLUMN public.system_alerts.message IS 'A human-readable message describing the alert.';
COMMENT ON COLUMN public.system_alerts.context IS 'The full JSON payload or relevant context for the alert.';
COMMENT ON COLUMN public.system_alerts.status IS 'The status of the alert (new, acknowledged, resolved).';
COMMENT ON COLUMN public.system_alerts.work_order_number IS 'The work order number associated with the alert for easy lookup.'; 