name: Trigger Vercel Sync

on:
  schedule:
    # Runs every 10 minutes
    - cron: '*/10 * * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  trigger-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Call Vercel Sync Endpoint
        run: 'curl -X POST -H "Authorization: Bearer ${{ secrets.VERCEL_AUTOMATION_TOKEN }}" https://go-blinds-smart-system.vercel.app/api/google-sheets/sync' 